### ISSUE TITLE
Request to collaborate

### ISSUE THREAD

**Issue by senabac** [impact-initiatives-geospatial/git_demo#6]
Hi. Can you add me as a collaborator?

**Comment by zackarno** [comment]
Yea sure. First I should invite you to be a member of the `impact-initiatives-geospatial` page. Then I will give you write access. Let me know when you accept the first invitation

**Comment by senabac** [comment]
Sure! Invitation accepted.

**Comment by zackarno** [comment]
great - you now have write access.

- [ ]  clone
- [ ] make branch
- [ ] drop a text file in repo (in branch)
- [ ] commit with message
- [ ] push
- [ ] pull request
- [ ] merge gets approved
- [ ] you merge  & delete branch
